### ISSUE TITLE
Scroll 

### ISSUE THREAD

**Issue by dmzx** [kasimi/mChat#1]
> Is there any special content (BBCode, image, content from another extension) in those messages that stop the auto-scrolling?

I can reproduce this with a flash bbcode only on firefox.
Scroll will not go whole the way down when reload page.

**Comment by kasimi** [comment]
I can reproduce the issue when posting a YouTube video with the s9e/mediaembed extension enabled. With the above linked commit the container keeps scrolling until the bottom is reached, the issue seems fixed for me. Give it a try and let me know.

**Comment by dmzx** [comment]
indeed the s9e/mediaembed extension is also enabled.
Still it wont scroll down only in firefox, in chrome its ok.

![chat](https://cloud.githubusercontent.com/assets/6445099/18814110/79cf2d68-8310-11e6-9307-f5a91609443e.PNG)

**Comment by kasimi** [comment]
Do you know if this problem also existed in RC5, or was it introduced in RC6?

**Comment by dmzx** [comment]
Will install RC5 with s9e/mediaembed extension and double check it.

**Comment by dmzx** [comment]
Tested with RC5 and have same problem in Firefox, chrome is ok.

![knipsel](https://cloud.githubusercontent.com/assets/6445099/18815924/629cca14-833e-11e6-809c-069c761ebccb.PNG)

**Comment by kasimi** [comment]
I can't reproduce this on RC6 with the above fix applied. I'm testing in Firefox with YouTube links and it always scrolls to the bottom. :neutral_face:

**Comment by dmzx** [comment]
I tried al the time with the [flash=][/flash] bbcode did you do that also?

**Comment by kasimi** [comment]
Ah ok, I see it now. It's the same problem that I've described here: https://www.phpbb.com/community/viewtopic.php?p=14526806#p14526806

The code would have to detect when the content has finished loading and only then trigger the scrolling. I'm not sure it's worth the effort.

**Comment by dmzx** [comment]
Ok clear close this one.

**Comment by kasimi** [comment]
Okay. If you have any ideas in the future how to improve the code feel free to open a new issue.
