### ISSUE TITLE
Forum which uses Canvas style doesn't work after installation mChat

### ISSUE THREAD

**Issue by ernestpasnik** [kasimi/mChat#11]
Hello. I'm trying to install mChat on the forum which uses Canvas style but there is a problem. Looks like only header is loaded and that's all. PHP error http://pastebin.com/ivEqTQyg

- PHP version 5.6.28
- Board version 3.1.10
- mChat version 2.0.0-RC7

**Comment by kasimi** [comment]
Can you check your `/styles/canvas/style.cfg` and see if there's a parent style defined? Also, what's your Canvas style version?

**Comment by ernestpasnik** [comment]
Yeah, content of the file:
```
name = Canvas
copyright = © slickthemes.co 2016
style_version = 1.2.0
phpbb_version = 3.1.6
parent = prosilver
```

**Comment by kasimi** [comment]
When I delete my `mchat.css` file I get this error:

`Unable to find template "@dmzx_mchat/mchat.css" (looked into: ./ext/dmzx/mchat/styles/canvas/template, ./ext/dmzx/mchat/styles/canvas/theme, ./ext/dmzx/mchat/styles/prosilver/template, ./ext/dmzx/mchat/styles/prosilver/theme, ./ext/dmzx/mchat/styles/all/template, ./ext/dmzx/mchat/styles/all/template)`

As you can see it's looking in the correct places (`canvas`, `prosilver`, `all`), whereas your phpBB installation skips the `prosilver` folder.

Can you confirm that this SQL query returns `parent_name prosilver`?

`SELECT style_name as parent_name FROM phpbb_styles WHERE style_id = (SELECT style_parent_id FROM phpbb_styles WHERE style_path = 'canvas')`

**Comment by ernestpasnik** [comment]
Yeah that query returned 0 results. I set Inherits from: prosilver in canvas details and it works. Thank you for help!
