### ISSUE TITLE
Escaping js vars

### ISSUE THREAD

**Issue by Nicofuma** [kasimi/mChat#18]
Hi, just to let you know, when you are using a php value in a js script like here:
https://github.com/kasimi/mChat/blob/f6597758701c49cd3e52144cdb56d8b8e8f39e8f/core/mchat.php#L814
https://github.com/kasimi/mChat/blob/master/styles/all/template/mchat_script_data.html#L60

It is safer and easier to rely on Twig to escape the var than using addslashes. How?
1. Do nothing in PHP
2. In the template
     a. uses `mssgLngthLong	: '{{ A_MCHAT_MESS_LONG | e('js') }}',`
     b. alternative: use an autoescape block to set the escaping method (https://twig.symfony.com/doc/2.x/tags/autoescape.html)

**Comment by kasimi** [comment]
Thanks for your feedback! Now Twig is used in all template files and escaping is done like this:

https://github.com/kasimi/mChat/blob/a5e5370378b2264c9f1ab4e3775b66d2511b871d/core/mchat.php#L807
https://github.com/kasimi/mChat/blob/a5e5370378b2264c9f1ab4e3775b66d2511b871d/styles/all/template/mchat_script_data.html#L58

**Comment by Nicofuma** [comment]
:)
