### ISSUE TITLE
BBcode blocking

### ISSUE THREAD

**Issue by dmzx** [kasimi/mChat#2]
When Disallowed bbcode img you can still post img images.

**Comment by kasimi** [comment]
I can't test this at the moment, does it happen in 3.1? For 3.2 it was already [reported](https://www.phpbb.com/community/viewtopic.php?p=14527521#p14527521) and fixed in the dev branch: https://github.com/kasimi/mChat/commit/1562b75bf46e94a5b45ad27b0bf70ef7e380a3ce

**Comment by dmzx** [comment]
This is with latest dev branch on 3.2 tested.
Will check it on 3.1 also.

**Comment by kasimi** [comment]
It works as expected in 3.1 but I can confirm that 1562b75 (3.2) doesn't work for the [img] BBCode. I will investigate.

**Comment by kasimi** [comment]
5df9ae1 should fix the issue on 3.2.

**Comment by dmzx** [comment]
Confirmed on 3.2

![knipsel](https://cloud.githubusercontent.com/assets/6445099/18903477/b6ae4e30-8559-11e6-8622-92c64fa8fd30.PNG)

**Comment by kasimi** [comment]
As a side note, the blocking behavior is a little different on 3.2. While the tags of disallowed BBCodes are removed in 3.1, they are still printed in 3.2, but I think that's totally acceptable.

Closing for now.
