### ISSUE TITLE
Add support for Markdown extension

### ISSUE THREAD

**Issue by AlfredoRamos** [kasimi/mChat#27]
Hi,

I'm developing an extension to add Markdown support in posts, private messages and signature, however an user reported me that a custom posting editor option "Disable Markdown" is not working when having mChat enabled.

I could reproduce the issue by just installing and enabling mChat (2.1.2), I can't see where the problem is coming from, I've checked my event listener and the checks I'm doing return the expected values except from the one in `core.text_formatter_s9e_parser_setup`

So my questions are:

- Do you modify the post data before/after parsing?
- How can I add support to mChat?

I did a brief code review but I couldn't figure it out. I don't know why it conflicts with posts and private messages.

Setup:
- PHP 5.6.40
- PostgreSQL 11.1 / MariaDB 10.3.12
- phpBB 3.2.5 (clean install)
- Markdown 0.6.0-dev (still in development)
- mChat 2.1.2

References:
- [User report](https://www.phpbb.com/community/viewtopic.php?f=456&p=15196016&sid=3b2df81a9556a74e7bdf69720fa1109f#p15196016)
- [alfredoramos/markdown/event/listener.php](https://github.com/AlfredoRamos/phpbb-ext-markdown/blob/3644e7d43560e9a7b524bf2af5811992cd24ad21/event/listener.php)

**Comment by kasimi** [comment]
The event execution order is different.

With mChat disabled, `core.posting_modify_message_text` is triggered first, where you prepare the `$markdown_enabled` property according to the post options. Then, the `core.text_formatter_s9e_parser_setup` is triggered, where you use the `$markdown_enabled` value to disable markdown if necessary.

With mChat enabled, `core.text_formatter_s9e_parser_setup` is triggered first and it uses the `$markdown_enabled` value that was set up in your listener's constructor. mChat's [notification service has a dependency on the parser](https://github.com/kasimi/mChat/blob/2.1.2/config/services.yml#L41). Apparently, mChat's notification service is requested at an earlier stage than `posting.php` is requesting the parser service, which messes up the event execution order which your extension depends on.

Maybe this could work as a solution: in your `core.text_formatter_s9e_parser_setup` event, do `$this->parser = $event['parser']->get_parser();` and use `$this->parser` to disable the plugins in your `core.posting_modify_message_text` event handler.

Alternatively, I could remove the `@text_formatter.parser` dependency from mChat's notification service and get it from the container on-demand.

Regarding supporting mChat in your extension, you should be able to use the `core.modify_text_for_storage_before` event and check for `$event['mode'] == 'mchat'` to enable markdown mode.

**Comment by AlfredoRamos** [comment]
Hi @kasimi 

Thanks for the explanation, now I get it.

I tried the workaround you proposed about creating a class property `$parser` and initialize it in `core.text_formatter_s9e_parser_setup` to use it in `core.posting_modify_message_text`, but when I do:

```php
// core.posting_modify_message_text callback

		$this->markdown_enabled = $this->markdown_enabled &&
			!empty($this->auth->acl_get('f_markdown', $event['forum_id'])) &&
			!empty($event['post_data']['enable_markdown']);

		if (!$this->markdown_enabled)
		{
			$this->parser->disablePlugin('Litedown');
			$this->parser->disablePlugin('PipeTables');
		}
```

I get:

```
 Fatal error: Call to a member function disablePlugin() on null in /srv/http/forum/ext/alfredoramos/markdown/event/listener.php on line 299
```

Looks like `core.posting_modify_message_text` is called before `core.text_formatter_s9e_parser_setup` where I initialize `$this->parser`

For reference, this what I used:

<details>
<summary>Modifier event/listener.php</summary>

```php
<?php

/**
 * Markdown extension for phpBB.
 * @author Alfredo Ramos <alfredo.ramos@yandex.com>
 * @copyright 2019 Alfredo Ramos
 * @license GPL-2.0-only
 */

namespace alfredoramos\markdown\event;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use phpbb\auth\auth;
use phpbb\config\config;
use phpbb\user;
use phpbb\request\request;
use phpbb\template\template;
use phpbb\routing\helper as routing_helper;
use phpbb\language\language;
use alfredoramos\markdown\includes\helper;

class listener implements EventSubscriberInterface
{
	/** @var \phpbb\auth\auth */
	protected $auth;

	/** @var \phpbb\config\config */
	protected $config;

	/** @var \phpbb\user */
	protected $user;

	/** @var \phpbb\request\request */
	protected $request;

	/** @var \phpbb\template\template */
	protected $template;

	/** @var \phpbb\routing\helper */
	protected $routing_helper;

	/** @var \phpbb\language\language */
	protected $language;

	/** @var \alfredoramos\markdown\includes\helper */
	protected $helper;

	protected $parser;

	/** @var bool */
	private $markdown_enabled;

	/**
	 * Listener constructor.
	 *
	 * @param \phpbb\auth\auth			$auth
	 * @param \phpbb\config\config		$config
	 * @param \phpbb\user				$user
	 * @param \phpbb\request\request	$request
	 * @param \phpbb\template\template	$template
	 * @param \phpbb\routing\helper		$routing_helper
	 * @param \phpbb\language\language	$language
	 * @param \alfredoramos\markdown\includes\helper	$helper
	 *
	 * @return void
	 */
	public function __construct(auth $auth, config $config, user $user, request $request, template $template, routing_helper $routing_helper, language $language, helper $helper)
	{
		$this->auth = $auth;
		$this->config = $config;
		$this->user = $user;
		$this->request = $request;
		$this->template = $template;
		$this->routing_helper = $routing_helper;
		$this->language = $language;
		$this->helper = $helper;
		$this->markdown_enabled = !empty($this->config['allow_markdown']) &&
			!empty($this->auth->acl_get('u_markdown')) &&
			!empty($this->user->data['user_allow_markdown']);
	}

	/**
	 * Assign functions defined in this class to event listeners in the core.
	 *
	 * @return array
	 */
	static public function getSubscribedEvents()
	{
		return [
			// ...
			'core.text_formatter_s9e_configure_after' => 'configure_markdown',
			'core.text_formatter_s9e_parser_setup' => 'enable_markdown',
			// ...
			'core.posting_modify_message_text' => 'check_forum_permissions',
			// ...
		];
	}

	// ...

	/**
	 * Configure markdown.
	 *
	 * @param object $event
	 *
	 * @return void
	 */
	public function configure_markdown($event)
	{
		$configurator = $event['configurator'];

		if (!$this->markdown_enabled)
		{
			unset($configurator->Litedown);
			unset($configurator->PipeTables);
			return;
		}

		$configurator->Litedown;
		$configurator->PipeTables;
	}

	/**
	 * Enable markdown.
	 *
	 * @param object $event
	 *
	 * @return void
	 */
	public function enable_markdown($event)
	{
		$this->parser = $event['parser']->get_parser();

		// true, false
		//var_dump(isset($this->parser), is_null($this->parser));

		/*if (!$this->markdown_enabled)
		{
			$parser = $event['parser']->get_parser();
			$parser->disablePlugin('Litedown');
			$parser->disablePlugin('PipeTables');
		}*/
	}

	// ...

	/**
	 * Check Markdown forum permissions.
	 *
	 * @param object $event
	 *
	 * @return void
	 */
	public function check_forum_permissions($event)
	{
		$event['post_data'] = array_merge([
			'enable_markdown' => empty($this->request->variable('disable_markdown', false))
		], $event['post_data']);

		$this->markdown_enabled = $this->markdown_enabled &&
			!empty($this->auth->acl_get('f_markdown', $event['forum_id'])) &&
			!empty($event['post_data']['enable_markdown']);

		// false, true
		//var_dump(isset($this->parser), is_null($this->parser));

		if (!$this->markdown_enabled)
		{
			$this->parser->disablePlugin('Litedown');
			$this->parser->disablePlugin('PipeTables');
		}

		$this->template->assign_var(
			'S_MARKDOWN_CHECKED',
			empty($event['post_data']['enable_markdown']) ? ' checked="checked"' : ''
		);
	}

	// ...
}
```

</details>

___

I think I could use `$event['message_parser']` from `core.posting_modify_message_text` and `core.ucp_pm_compose_modify_parse_before`, but in the signature event I'm using (`core.ucp_profile_modify_signature`) there's no `$event['parser']` nor `$event['message_parser']`, it was removed in 3.2.0-RC2 (`@changed 3.2.0-RC2 Removed message parser`), so I would need to drop support for signatures, which I don't really want to.

**Comment by kasimi** [comment]
Ah yes, what I suggested only works if mChat is enabled. :laughing: 

I think the easiest solution is to inject the `@text_formatter.parser` service into your listener. The only concern this raises is performance: I don't know if it affects overall board performance if the parser is constructed on every request.

Edit: you could move your handlers for `core.user_setup` and `core.permissions` to a new listener. That way, your main listener and therefore the parser isn't instantiated on every request.

**Comment by AlfredoRamos** [comment]
I'm interested in the other possible solution you mentioned:

> Alternatively, I could remove the `@text_formatter.parser` dependency from mChat's notification service and get it from the container on-demand.

Would that honor the event order? wouldn't that break mChat? Because that looks like it would be a better solution.

**Comment by kasimi** [comment]
I just tested it and it works fine. However, I don't see why it's a better solution:

1. I missed the fact that with mChat enabled, mChat's services and therefore the parser instance are created on every request too, and I haven't noticed any notable performance impact.
2. Injecting dependencies is preferred over getting them from the container.
3. mChat is certainly not the only extension that injects the parser service. You have the same incompatibility problem with any extension that does this.

**Comment by AlfredoRamos** [comment]
I see.

I thought the change you mentioned would respect the event order, but it looks it will not.

I think that, for now, I won't add support for any other extension that changes that, I don't want to add extra verifications for that, besides I created that extension mainly for personal use.

Thanks.
