### ISSUE TITLE
'flood_time' max 60s

### ISSUE THREAD

**Issue by jbaiao** [kasimi/mChat#28]
Its possible to increse 'flood_time' more than 60s?
Tks

**Comment by kasimi** [comment]
Yes, see these changes: https://github.com/kasimi/mChat/commit/7b66a5a19d0dab7882903ed7a3075a3d37956d1c

For more than 1 hour, change the `3600` in `core/settings.php` to whatever number of seconds you need.

**Comment by jbaiao** [comment]
That its!
Tks!
