### ISSUE TITLE
Cant remove files.

### ISSUE THREAD

**Issue by AkelGP** [kasimi/mChat#29]
Hey, if i want to remove all files through ACP, my web browser tells me HTTP ERROR 500, This site isnt working. When i go back to ACP, mChat is still there. Last time i tried to remove it, i deleted it from FTP without removing files from ACP. Help please, how to uninstall it.

**Comment by kasimi** [comment]
Hi, what do you mean `remove all files through ACP`? Do you mean `delete data`? Check your server's error log. Do you have any mChat add-ons installed?

If you delete the extension files from your FTP before completely uninstalling the extension, you will break your board. Make sure you delete the extension data before removing any files.

**Comment by kasimi** [comment]
No feedback, closing.
