### ISSUE TITLE
Time out errors

### ISSUE THREAD

**Issue by dmzx** [kasimi/mChat#3]
**Got some members with time out errors:**

> Is this an Mchat error maybe? I'm getting it both here, and my own site.

![knipsel](https://cloud.githubusercontent.com/assets/6445099/18912020/86caf606-8580-11e6-9bc5-78a2cddf9fe3.PNG)

**Also reported:**

> I feel we need to improve overall error handling before releasing. 
> Simple test:
> 1) publish some message in chat, wait for it to appear
> 2) disconnect internet, while keeping chat visible
> Outcome: you will get undefined error or timeout error in best case. Imo, we should not throw error in such situation, be consistent with phpBB behavior..

In logs:

`jquery.min.js?assets_version=69:4 XHR finished loading: POST "http://www.sample.org/forum/mchat/action/refresh".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
jquery.min.js?assets_version=69:4 POST http://www.sample.org/forum/mchat/action/refresh net::ERR_NAME_NOT_RESOLVEDsend @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
jquery.min.js?assets_version=69:4 XHR failed loading: POST "http://www.sample.org/forum/mchat/action/refresh".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
mchat.js?assets_version=69:116 AJAX error. status: error, message:  ()
jquery.min.js?assets_version=69:4 POST http://www.sample.org/forum/mchat/action/refresh net::ERR_INTERNET_DISCONNECTEDsend @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
jquery.min.js?assets_version=69:4 XHR failed loading: POST "http://www.sample.org/forum/mchat/action/refresh".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
mchat.js?assets_version=69:116 AJAX error. status: error, message:  ()
jquery.min.js?assets_version=69:4 POST http://www.sample.org/forum/mchat/action/refresh net::ERR_INTERNET_DISCONNECTEDsend @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
jquery.min.js?assets_version=69:4 XHR failed loading: POST "http://www.sample.org/forum/mchat/action/refresh".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
mchat.js?assets_version=69:116 AJAX error. status: error, message:  ()
jquery.min.js?assets_version=69:4 POST http://www.sample.org/forum/mchat/action/whois net::ERR_INTERNET_DISCONNECTEDsend @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86whois @ mchat.js?assets_version=69:324
jquery.min.js?assets_version=69:4 XHR failed loading: POST "http://www.sample.org/forum/mchat/action/whois".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86whois @ mchat.js?assets_version=69:324
mchat.js?assets_version=69:116 AJAX error. status: error, message:  ()
undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().
jquery.min.js?assets_version=69:4 POST http://www.sample.org/forum/mchat/action/refresh net::ERR_INTERNET_DISCONNECTEDsend @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
jquery.min.js?assets_version=69:4 XHR failed loading: POST "http://www.sample.org/forum/mchat/action/refresh".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
mchat.js?assets_version=69:116 AJAX error. status: error, message:  ()
jquery.min.js?assets_version=69:4 POST http://www.sample.org/forum/mchat/action/refresh net::ERR_INTERNET_DISCONNECTEDsend @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
jquery.min.js?assets_version=69:4 XHR failed loading: POST "http://www.sample.org/forum/mchat/action/refresh".send @ jquery.min.js?assets_version=69:4ajax @ jquery.min.js?assets_version=69:4ajaxRequest @ mchat.js?assets_version=69:86refresh @ mchat.js?assets_version=69:295
mchat.js?assets_version=69:116 AJAX error. status: error, message:  ()`

I have also experienced some logouts on my website, is the time out handled to quick maybe?

**Comment by kasimi** [comment]
The timeout is the same as the refresh interval as defined in the ACP, but not more than 10 seconds: https://github.com/kasimi/mChat/blob/2.0.0-RC6/styles/all/template/javascript/mchat.js#L88 I think 10 seconds is more than enough to allow a request to complete.

Is your refresh rate longer than 10 seconds? If not try to increase it.

I agree that a popup for timeout errors is too aggressive. I'll see if there's a way to suppress it in that case.

Can you elaborate on your problem with logouts? When do they happen? Are you sure they are related to mChat?

**Comment by dmzx** [comment]
Will do some checking, it appears when disabling or purge cache it will take a long time to refresh the page.

**Comment by ghost** [comment]
I have the same problem with rc6 in root but with the site cloned and in a folder no time outs no errors via popups  when in root host cpu runs at 45% and i have turbo servers  out of root perfect i put rc5 back on in root perfect.

**Comment by kasimi** [comment]
With the above linked change timeout and unknown errors (for example disconnected internet) won't display a popup any more. Note that this doesn't solve the cause of the problem, it's just a cosmetic fix.

@martin123456 Interesting observation. All of my phpBB boards where mChat is installed run in a sub-directory so I haven't noticed anything out of the ordinary. I will test this in the root folder and report back.

Out of curiosity, what's your refresh interval? And when you saw the high CPU load:
- how many users were online, i.e. reading the chat?
- how many users were actively chatting?

**Comment by ghost** [comment]
Refresh is 10 seconds there is never any more then 3 or 4 in chat 

cpu is  random in the image at the start of the day is rc5 you can see when rc6 went on lol 

http://www.martins-homelinux.net/images/tempuploads/1475145728.png

RC6 is stable when in subdirectory  site is heavy on ext's so cloned the site to subdirectory and perfect there 

Edit: made the changes to mchat.js  cpu has total drop and no time out errors left pc on went to bed got up and still in chat and working ok.

**Comment by kasimi** [comment]
Good to know about the timeout errors, but what do you mean by "cpu has total drop"? Did updating `mchat.js` make the CPU usage go back to normal?

**Comment by ghost** [comment]
Yes all the way down to 11% massive drop i sat at 11% of cpu usage on rc5 too.

**Comment by kasimi** [comment]
I have no idea how that could have fixed it but I'm glad it's all good now, thanks for testing.

If you notice any problems with CPU load in the future feel free to open a new issue.
