### ISSUE TITLE
General Error

### ISSUE THREAD

**Issue by AkelGP** [kasimi/mChat#30]
Hello, if i try to get in extensions to mChat, i will get this error:

```
General Error
Module not accessible
BACKTRACE
FILE: (not given by php)

LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions_module.php
LINE: 565
CALL: trigger_error()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()
```

How can i repair it?

**Comment by kasimi** [comment]
Go to ACP, System tab, Module Management for the ACP, go to the Extensions module and make sure that all mChat modules are installed and enabled.

**Comment by AkelGP** [comment]
Everything enabked. But it works now. I just disabled and enabled it. 😂. Thanks.
