### ISSUE TITLE
Version 2.1.4-RC1 active_users error

### ISSUE THREAD

**Issue by dmzx** [kasimi/mChat#35]
Got this error 

> /ext/dmzx/mchat/core/mchat.php on line 754: compact(): Undefined variable: active_users

 when switched off in ACP Global settings:

> Display number of active chat sessions in the navbar

https://github.com/kasimi/mChat/blob/dev/core/mchat.php#L730

**Comment by kasimi** [comment]
Thanks, the fix is linked above.
