### ISSUE TITLE
update for phpBB 3.3.1

### ISSUE THREAD

**Issue by bug-i** [kasimi/mChat#36]
White screen of death at my installation after the latest update to phpBB 3.3.1
Must be related to mchat, already deactivated all other extensions and now only have mchat active -> Whitescreen.
After deactivation of mchat and clearing cache everything is back to normal

**Comment by juanpa669** [comment]
Same here, mChat caused forum crash.

Will there be an update or the project has been stopped?

**Comment by kasimi** [comment]
The [master](https://github.com/kasimi/mChat/tree/master) branch only has the latest _stable_ changes, i.e. validated by phpbb.com. Check the [dev](https://github.com/kasimi/mChat/tree/dev) branch for the latest _unvalidated_ changes. There is a [2.1.4-RC2](https://github.com/kasimi/mChat/releases/tag/2.1.4-RC2) version that is compatible with phpBB 3.3.x.

**Comment by kasimi** [comment]
The final version 2.1.4 is now available. If you still have problems running mChat 2.1.4 on phpBB 3.3.x, please open a new issue.
