### ISSUE TITLE
Error when activate mChat 2.1.4 on phpBB 3.3.1

### ISSUE THREAD

**Issue by juanpa669** [kasimi/mChat#38]
Hello,

I got a error message when I try to activate mChat 2.1.4 on my board version 3.3.1

I had delete  data, remove extension, re upload the new one, clear the cache etc...

How can I fix it please

Thanks 
`
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "dmzx.mchat.cron.task.mchat_prune", path: "dmzx.mchat.cron.task.mchat_prune -> dmzx.mchat.functions -> dmzx.mchat.notifications -> text_formatter.s9e.parser -> dmzx.mchat.cron.task.mchat_prune". in /htdocs/my-domain.com/forum/vendor/symfony/dependency-injection/Container.php:297 Stack trace: #0 /htdocs/my-domain.com/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(606): Symfony\Component\DependencyInjection\Container->get('dmzx.mchat.cron...', 2) #1 /htdocs/my-domain.com/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet('dmzx.mchat.cron...', 1) #2 /htdocs/my-domain.com/forum/phpbb/di/service_collection.php(57): Symfony\Component\DependencyInjection\ContainerBuilder->get('dmzx.mchat.cron...') #3 /htdocs/my-domain.com/forum/phpbb/di/service_collection_iterator.php(44): phpbb\di\service_collect in /htdocs/my-domain.com/forum/vendor/symfony/dependency-injection/Container.php on line 297`

**Comment by kasimi** [comment]
You need to update the ABBC3 extension to the latest version. See here: https://www.phpbb.com/customise/db/extension/mchat_extension/support/topic/220581

**Comment by juanpa669** [comment]
Thank you so much !
